---

- name: config spines
  eos_config:
    src: spine.j2
  register: output
  
- name: changes performed
  debug:
    msg: "{{ output.commands }}"
  when: output.commands is defined

- name: save config
  eos_config:
    lines: wr
