all:
  children:
    spines:
      hosts:
        S1:
          router_id: 10.0.255.1
          interfaces:
            Ethernet1:
              ipv4: 10.1.11.1/24
            Ethernet2:
              ipv4: 10.1.12.1/24
            Ethernet3:
              ipv4: 10.1.13.1/24
            Ethernet4:
              ipv4: 10.1.14.1/24
        S2:
          router_id: 10.0.255.2
          interfaces:
            Ethernet1:
              ipv4: 10.2.11.2/24
            Ethernet2:
              ipv4: 10.2.12.2/24
            Ethernet3:
              ipv4: 10.2.13.2/24
            Ethernet4:
              ipv4: 10.2.14.2/24
        S3:
          router_id: 10.0.255.3
          interfaces:
            Ethernet1:
              ipv4: 10.3.15.3/24
            Ethernet2:
              ipv4: 10.3.16.3/24
            Ethernet3:
              ipv4: 10.3.17.3/24
            Ethernet4:
              ipv4: 10.3.18.3/24
        S4:
          router_id: 10.0.255.4
          interfaces:
            Ethernet1:
              ipv4: 10.4.15.4/24
            Ethernet2:
              ipv4: 10.4.16.4/24
            Ethernet3:
              ipv4: 10.4.17.4/24
            Ethernet4:
              ipv4: 10.4.18.4/24
    leafs:
      children:
        border_leafs:
          children:
            L2:
              vars:
                mlag_id: 10.0.254.2
              hosts:
                L2A-13:
                  router_id: 10.0.255.13
                  interfaces:
                    Ethernet2:
                      ipv4: 10.1.13.13/24
                    Ethernet3:
                      ipv4: 10.2.13.13/24
                    Ethernet4:
                      ipv4: 10.13.15.13/24
                    Ethernet5:
                      ipv4: 10.13.16.13/24
                L2B-14:
                  router_id: 10.0.255.14
                  interfaces:
                    Ethernet2:
                      ipv4: 10.1.14.14/24
                    Ethernet3:
                      ipv4: 10.2.14.14/24
                    Ethernet4:
                      ipv4: 10.14.16.14/24
                    Ethernet5:
                      ipv4: 10.14.15.14/24
            L3:
              vars:
                mlag_id: 10.0.254.3
              hosts:
                L3A-15:
                  router_id: 10.0.255.15
                  interfaces:
                    Ethernet2:
                      ipv4: 10.3.15.15/24
                    Ethernet3:
                      ipv4: 10.4.15.15/24
                    Ethernet4:
                      ipv4: 10.13.15.15/24
                    Ethernet5:
                      ipv4: 10.14.15.15/24
                L3B-16:
                  router_id: 10.0.255.16
                  interfaces:
                    Ethernet2:
                      ipv4: 10.3.16.16/24
                    Ethernet3:
                      ipv4: 10.4.16.16/24
                    Ethernet4:
                      ipv4: 10.14.16.16/24
                    Ethernet5:
                      ipv4: 10.13.16.16/24
        L1:
          vars:
            mlag_id: 10.0.254.1
          hosts:
            L1A-11:
              router_id: 10.0.255.11
              interfaces:
                Ethernet2:
                  ipv4: 10.1.11.11/24
                Ethernet3:
                  ipv4: 10.2.11.11/24
            L1B-12:
              router_id: 10.0.255.12
              interfaces:
                Ethernet2:
                  ipv4: 10.1.12.12/24
                Ethernet3:
                  ipv4: 10.2.12.12/24
        L4:
          vars:
            mlag_id: 10.0.254.4
          hosts:
            L4A-17:
              router_id: 10.0.255.17
              interfaces:
                Ethernet2:
                  ipv4: 10.3.17.17/24
                Ethernet3:
                  ipv4: 10.4.17.17/24
            L4B-18:
              router_id: 10.0.255.18
              interfaces:
                Ethernet2:
                  ipv4: 10.3.18.18/24
                Ethernet3:
                  ipv4: 10.4.18.18/24