all:
  children:
    spines:
      hosts:
        S1: 
          router_id: 10.255.255.1
          interfaces:
            Ethernet3: 
              ipv4: 10.1.3.1/24
            Ethernet4: 
              ipv4: 10.1.4.1/24
            Ethernet5: 
              ipv4: 10.1.5.1/24
            Ethernet6: 
              ipv4: 10.1.6.1/24
            Ethernet7: 
              ipv4: 10.1.7.1/24
            Ethernet8: 
              ipv4: 10.1.8.1/24
        S2:
          router_id: 10.255.255.2
          interfaces:
            Ethernet3:
              ipv4: 10.2.3.2/24
            Ethernet4: 
              ipv4: 10.2.4.2/24
            Ethernet5: 
              ipv4: 10.2.5.2/24
            Ethernet6: 
              ipv4: 10.2.6.2/24
            Ethernet7: 
              ipv4: 10.2.7.2/24
            Ethernet8: 
              ipv4: 10.2.8.2/24
        S9: 
          router_id: 10.255.255.9
          interfaces:
            Ethernet1: 
              ipv4: 10.9.11.9/24
            Ethernet2: 
              ipv4: 10.9.12.9/24
            Ethernet3: 
              ipv4: 10.9.13.9/24
            Ethernet4: 
              ipv4: 10.9.14.9/24
        S10:
          router_id: 10.255.255.10
          interfaces:
            Ethernet1:
              ipv4: 10.10.11.10/24
            Ethernet2: 
              ipv4: 10.10.12.10/24
            Ethernet3: 
              ipv4: 10.10.13.10/24
            Ethernet4: 
              ipv4: 10.10.14.10/24
    leafs:
      vars:
        vlans: &vlans
          10:
            ipv4_virtual: 10.0.10.1/24
            vrf: A
            trunk:
              groups:
                - ESX
          20:
            ipv4_virtual: 10.0.20.1/24
            vrf: A
            trunk:
              groups:
                - ESX
          30:
            ipv4_virtual: 10.0.30.1/24
            vrf: B
            trunk:
              groups:
                - ESX
          40:
            ipv4_virtual: 10.0.40.1/24
            vrf: B
            trunk:
              groups:
                - ESX
      children:
        border_leafs:
          children:
            L1:
              hosts:
                L1A-3:
                  router_id: 10.255.255.3
                  vlans:
                    <<: *vlans
                    3000:
                      ipv4: 172.31.0.2/29
                      vrf: A
                      trunk:
                        groups:
                          - FW
                    3001:
                      ipv4: 172.31.0.10/29
                      vrf: B
                      trunk:
                        groups:
                          - FW
                  interfaces:
                    Ethernet2:
                      ipv4: 10.1.3.3/24
                    Ethernet3:
                      ipv4: 10.2.3.3/24
                    Ethernet6:
                      ipv4: 10.3.11.3/24
                    Ethernet7:
                      ipv4: 10.3.12.3/24
                L1B-4:
                  router_id: 10.255.255.4
                  vlans:
                    <<: *vlans
                    3000:
                      ipv4: 172.31.0.3/29
                      vrf: A
                      trunk:
                        groups:
                          - FW
                    3001:
                      ipv4: 172.31.0.11/29
                      vrf: B
                      trunk:
                        groups:
                          - FW
                  interfaces:
                    Ethernet2:
                      ipv4: 10.1.4.4/24
                    Ethernet3:
                      ipv4: 10.2.4.4/24
                    Ethernet6:
                      ipv4: 10.4.12.4/24
                    Ethernet7:
                      ipv4: 10.4.11.4/24
            L4:
              hosts:
                L4A-11:
                  router_id: 10.255.255.11
                  vlans:
                    <<: *vlans
                    3000:
                      ipv4: 172.31.0.4/29
                      vrf: A
                      trunk:
                        groups:
                          - FW
                    3001:
                      ipv4: 172.31.0.12/29
                      vrf: B
                      trunk:
                        groups:
                          - FW
                  interfaces:
                    Ethernet2:
                      ipv4: 10.9.11.11/24
                    Ethernet3:
                      ipv4: 10.10.11.11/24
                    Ethernet6:
                      ipv4: 10.3.11.11/24
                    Ethernet7:
                      ipv4: 10.4.11.11/24
                L4B-12:
                  router_id: 10.255.255.12
                  vlans:
                    <<: *vlans
                    3000:
                      ipv4: 172.31.0.5/29
                      vrf: A
                      trunk:
                        groups:
                          - FW
                    3001:
                      ipv4: 172.31.0.13/29
                      vrf: B
                      trunk:
                        groups:
                          - FW
                  interfaces:
                    Ethernet2:
                      ipv4: 10.9.12.12/24
                    Ethernet3:
                      ipv4: 10.10.12.12/24
                    Ethernet6:
                      ipv4: 10.4.12.12/24
                    Ethernet7:
                      ipv4: 10.3.12.12/24
        internal_leafs:
          children:
            L2:
              hosts:
                L2A-5:
                  router_id: 10.255.255.5
                  interfaces:
                    Ethernet2:
                      ipv4: 10.1.5.5/24
                    Ethernet3:
                      ipv4: 10.2.5.5/24
                L2B-6:
                  router_id: 10.255.255.6
                  interfaces:
                    Ethernet2:
                      ipv4: 10.1.6.6/24
                    Ethernet3:
                      ipv4: 10.2.6.6/24
            L3:
              hosts:
                L3A-7:
                  router_id: 10.255.255.7
                  interfaces:
                    Ethernet2:
                      ipv4: 10.1.7.7/24
                    Ethernet3:
                      ipv4: 10.2.7.7/24
                L3B-8:
                  router_id: 10.255.255.8
                  interfaces:
                    Ethernet2:
                      ipv4: 10.1.8.8/24
                    Ethernet3:
                      ipv4: 10.2.8.8/24
            L5:
              hosts:
                L5A-13:
                  router_id: 10.255.255.13
                  interfaces:
                    Ethernet2:
                      ipv4: 10.9.13.13/24
                    Ethernet3:
                      ipv4: 10.10.13.13/24
                L5B-14:
                  router_id: 10.255.255.14
                  interfaces:
                    Ethernet2:
                      ipv4: 10.9.14.14/24
                    Ethernet3:
                      ipv4: 10.10.14.14/24